# Generated by Django 6.1 on 2026-09-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_detallepedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
    ]
